// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOs2EF9RdJ5X-LXe2gQ0cwbMeu9j7YVWo',
    appId: '1:915613659303:web:f03efd513317e0cab7eb82',
    messagingSenderId: '915613659303',
    projectId: 'geteidea',
    authDomain: 'geteidea.firebaseapp.com',
    storageBucket: 'geteidea.appspot.com',
    measurementId: 'G-RJP3HQMNQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsyBR6HUGuujx4gXzA0fEGIj67HE_Dt5E',
    appId: '1:915613659303:android:b00d82fa5e27424cb7eb82',
    messagingSenderId: '915613659303',
    projectId: 'geteidea',
    storageBucket: 'geteidea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA54FszRvzuEwLCVTdrd7OMdc4R1QC80hM',
    appId: '1:915613659303:ios:5e6e71cce5fe7fdfb7eb82',
    messagingSenderId: '915613659303',
    projectId: 'geteidea',
    storageBucket: 'geteidea.appspot.com',
    iosBundleId: 'com.example.geteideaTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA54FszRvzuEwLCVTdrd7OMdc4R1QC80hM',
    appId: '1:915613659303:ios:5e6e71cce5fe7fdfb7eb82',
    messagingSenderId: '915613659303',
    projectId: 'geteidea',
    storageBucket: 'geteidea.appspot.com',
    iosBundleId: 'com.example.geteideaTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOs2EF9RdJ5X-LXe2gQ0cwbMeu9j7YVWo',
    appId: '1:915613659303:web:3e1e711e035caecab7eb82',
    messagingSenderId: '915613659303',
    projectId: 'geteidea',
    authDomain: 'geteidea.firebaseapp.com',
    storageBucket: 'geteidea.appspot.com',
    measurementId: 'G-9FXY6R0LX9',
  );
}
